<?php include_once "DBData.php";

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;

include_once 'PHPMailer/Exception.php';
include_once 'PHPMailer/PHPMailer.php';
include_once 'PHPMailer/SMTP.php';

$existeError = false;
$emailSent = false;

if (isset($_POST["sendMailLowStockEmail"]) && connection_status() == 0) {
	$productsList = '';

	$sql = "SELECT nombre, precio, barcode, stock, activo FROM trvsol_products WHERE activo=1 AND stock <= 3 ORDER BY stock ASC";
	$result = $conn->query($sql);

	if ($result->num_rows > 0) {
		while ($row = $result->fetch_assoc()) {
			$productsList .= '<tr>
	<td>' . $row["stock"] . '</td>
	<td>' . $row["nombre"] . '<br>' . $row["barcode"] . '<br>$' . number_format($row["precio"], 0, ",", ".") . '</td>
	</tr>';
		}
	}

	if ($productsList != "") {
		$mail = new PHPMailer(true);
		try {
			$mail->SMTPDebug = SMTP::DEBUG_SERVER;
			$mail->SMTPDebug = 0;
			$mail->isSMTP();
			$mail->Host = phpmailer_host;
			$mail->SMTPAuth = true;
			$mail->Username = phpmailer_username;
			$mail->Password = phpmailer_password;
			$mail->SMTPSecure = PHPMailer::ENCRYPTION_SMTPS;
			$mail->Port = 465;

			//Recipients
			$mail->setFrom(phpmailer_username, 'POS System by TRV Solutions');
			$mail->addAddress($_POST["sendMailLowStockEmail"]);

			// Content
			$mail->isHTML(true);
			$mail->Subject = 'Low Stock Products - ' . date("d-m-Y");
			$mail->Body = '<html>
			<head>
			<meta charset= "UTF-8">
			<meta name= "viewport" content= "width=device-width, initial-scale=1">
			<title>Low Stock Products</title>
			<style>
			table{
			border-collapse: collapse;
			width: 90%;
			margin: auto;
			}
			
			th, td{
			border: 2px solid #c9cdcf;
			text-align: left;
			padding: 8px;
			}
			
			th{ background-color: #c9cdcf; }
			</style>
			</head>
			<body style= "background-color: #e6e7e8;text-align: center;">
			<div style= "max-width: 640px;background-color: #fff;margin: auto;">
			<img src= "/trv/media/banner-email.webp" style= "width: 100%;" alt= "Logo TRV Solutions">
			
			<h1 style= "margin-bottom: 2px;">Low stock products detected</h1>
			<p style= "margin-top: 2px;">We notify you that one or more products in your inventory are low in stock or completely out of stock, which you can see below.</p>
			
			<h3>Out of stock or nearly out of stock products - ' . date("d-m-Y") . '</h3>
			<table>
			<tr>
			<th>Current Stock</th>
			<th>Product Information</th>
			</tr>
			
			' . $productsList . '
			</table>
			<hr>
			<p style= "text-align: center;">This email has been automatically generated by <a href= "https://www.trvsolutions.com" target= "_blank">TRV Solutions</a>.</p>
			</div>
			</body>
			</html>';

			$mail->send();
			$emailSent = true;
		} catch (Exception $e) {
			$emailSent = false;
		}
	}
} else {
	$existeError = true;
}

$varsSend = array(
	'errores' => $existeError,
	'email_enviado' => $emailSent
);
echo json_encode($varsSend);
?>